/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WallRouteImport } from './routes/wall'
import { Route as TokenUsageRouteImport } from './routes/token-usage'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as ApiGuestbookRouteImport } from './routes/api/guestbook'
import { Route as MainTalksRouteImport } from './routes/_main/talks'
import { Route as MainLoginRouteImport } from './routes/_main/login'
import { Route as MainGuestbookRouteImport } from './routes/_main/guestbook'
import { Route as MainBlogRouteImport } from './routes/_main/blog'
import { Route as MainArchiveRouteImport } from './routes/_main/archive'
import { Route as MainSplatRouteImport } from './routes/_main/$'
import { Route as MainThoughtsIndexRouteImport } from './routes/_main/thoughts/index'
import { Route as ApiSignatureUploadRouteImport } from './routes/api/signature/upload'
import { Route as ApiGuestbookSignRouteImport } from './routes/api/guestbook/sign'
import { Route as ApiGuestbookCheckEligibilityRouteImport } from './routes/api/guestbook/check-eligibility'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as MainThoughtsSplatRouteImport } from './routes/_main/thoughts/$'
import { Route as MainPostsSplatRouteImport } from './routes/_main/posts/$'

const WallRoute = WallRouteImport.update({
  id: '/wall',
  path: '/wall',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenUsageRoute = TokenUsageRouteImport.update({
  id: '/token-usage',
  path: '/token-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const ApiGuestbookRoute = ApiGuestbookRouteImport.update({
  id: '/api/guestbook',
  path: '/api/guestbook',
  getParentRoute: () => rootRouteImport,
} as any)
const MainTalksRoute = MainTalksRouteImport.update({
  id: '/talks',
  path: '/talks',
  getParentRoute: () => MainRoute,
} as any)
const MainLoginRoute = MainLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MainRoute,
} as any)
const MainGuestbookRoute = MainGuestbookRouteImport.update({
  id: '/guestbook',
  path: '/guestbook',
  getParentRoute: () => MainRoute,
} as any)
const MainBlogRoute = MainBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => MainRoute,
} as any)
const MainArchiveRoute = MainArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => MainRoute,
} as any)
const MainSplatRoute = MainSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => MainRoute,
} as any)
const MainThoughtsIndexRoute = MainThoughtsIndexRouteImport.update({
  id: '/thoughts/',
  path: '/thoughts/',
  getParentRoute: () => MainRoute,
} as any)
const ApiSignatureUploadRoute = ApiSignatureUploadRouteImport.update({
  id: '/api/signature/upload',
  path: '/api/signature/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGuestbookSignRoute = ApiGuestbookSignRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => ApiGuestbookRoute,
} as any)
const ApiGuestbookCheckEligibilityRoute =
  ApiGuestbookCheckEligibilityRouteImport.update({
    id: '/check-eligibility',
    path: '/check-eligibility',
    getParentRoute: () => ApiGuestbookRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MainThoughtsSplatRoute = MainThoughtsSplatRouteImport.update({
  id: '/thoughts/$',
  path: '/thoughts/$',
  getParentRoute: () => MainRoute,
} as any)
const MainPostsSplatRoute = MainPostsSplatRouteImport.update({
  id: '/posts/$',
  path: '/posts/$',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/token-usage': typeof TokenUsageRoute
  '/wall': typeof WallRoute
  '/$': typeof MainSplatRoute
  '/archive': typeof MainArchiveRoute
  '/blog': typeof MainBlogRoute
  '/guestbook': typeof MainGuestbookRoute
  '/login': typeof MainLoginRoute
  '/talks': typeof MainTalksRoute
  '/api/guestbook': typeof ApiGuestbookRouteWithChildren
  '/posts/$': typeof MainPostsSplatRoute
  '/thoughts/$': typeof MainThoughtsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/guestbook/check-eligibility': typeof ApiGuestbookCheckEligibilityRoute
  '/api/guestbook/sign': typeof ApiGuestbookSignRoute
  '/api/signature/upload': typeof ApiSignatureUploadRoute
  '/thoughts/': typeof MainThoughtsIndexRoute
}
export interface FileRoutesByTo {
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/token-usage': typeof TokenUsageRoute
  '/wall': typeof WallRoute
  '/$': typeof MainSplatRoute
  '/archive': typeof MainArchiveRoute
  '/blog': typeof MainBlogRoute
  '/guestbook': typeof MainGuestbookRoute
  '/login': typeof MainLoginRoute
  '/talks': typeof MainTalksRoute
  '/api/guestbook': typeof ApiGuestbookRouteWithChildren
  '/': typeof MainIndexRoute
  '/posts/$': typeof MainPostsSplatRoute
  '/thoughts/$': typeof MainThoughtsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/guestbook/check-eligibility': typeof ApiGuestbookCheckEligibilityRoute
  '/api/guestbook/sign': typeof ApiGuestbookSignRoute
  '/api/signature/upload': typeof ApiSignatureUploadRoute
  '/thoughts': typeof MainThoughtsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/token-usage': typeof TokenUsageRoute
  '/wall': typeof WallRoute
  '/_main/$': typeof MainSplatRoute
  '/_main/archive': typeof MainArchiveRoute
  '/_main/blog': typeof MainBlogRoute
  '/_main/guestbook': typeof MainGuestbookRoute
  '/_main/login': typeof MainLoginRoute
  '/_main/talks': typeof MainTalksRoute
  '/api/guestbook': typeof ApiGuestbookRouteWithChildren
  '/_main/': typeof MainIndexRoute
  '/_main/posts/$': typeof MainPostsSplatRoute
  '/_main/thoughts/$': typeof MainThoughtsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/guestbook/check-eligibility': typeof ApiGuestbookCheckEligibilityRoute
  '/api/guestbook/sign': typeof ApiGuestbookSignRoute
  '/api/signature/upload': typeof ApiSignatureUploadRoute
  '/_main/thoughts/': typeof MainThoughtsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/token-usage'
    | '/wall'
    | '/$'
    | '/archive'
    | '/blog'
    | '/guestbook'
    | '/login'
    | '/talks'
    | '/api/guestbook'
    | '/posts/$'
    | '/thoughts/$'
    | '/api/auth/$'
    | '/api/guestbook/check-eligibility'
    | '/api/guestbook/sign'
    | '/api/signature/upload'
    | '/thoughts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/robots.txt'
    | '/sitemap.xml'
    | '/token-usage'
    | '/wall'
    | '/$'
    | '/archive'
    | '/blog'
    | '/guestbook'
    | '/login'
    | '/talks'
    | '/api/guestbook'
    | '/'
    | '/posts/$'
    | '/thoughts/$'
    | '/api/auth/$'
    | '/api/guestbook/check-eligibility'
    | '/api/guestbook/sign'
    | '/api/signature/upload'
    | '/thoughts'
  id:
    | '__root__'
    | '/_main'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/token-usage'
    | '/wall'
    | '/_main/$'
    | '/_main/archive'
    | '/_main/blog'
    | '/_main/guestbook'
    | '/_main/login'
    | '/_main/talks'
    | '/api/guestbook'
    | '/_main/'
    | '/_main/posts/$'
    | '/_main/thoughts/$'
    | '/api/auth/$'
    | '/api/guestbook/check-eligibility'
    | '/api/guestbook/sign'
    | '/api/signature/upload'
    | '/_main/thoughts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TokenUsageRoute: typeof TokenUsageRoute
  WallRoute: typeof WallRoute
  ApiGuestbookRoute: typeof ApiGuestbookRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiSignatureUploadRoute: typeof ApiSignatureUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wall': {
      id: '/wall'
      path: '/wall'
      fullPath: '/wall'
      preLoaderRoute: typeof WallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token-usage': {
      id: '/token-usage'
      path: '/token-usage'
      fullPath: '/token-usage'
      preLoaderRoute: typeof TokenUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/api/guestbook': {
      id: '/api/guestbook'
      path: '/api/guestbook'
      fullPath: '/api/guestbook'
      preLoaderRoute: typeof ApiGuestbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/talks': {
      id: '/_main/talks'
      path: '/talks'
      fullPath: '/talks'
      preLoaderRoute: typeof MainTalksRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/login': {
      id: '/_main/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof MainLoginRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/guestbook': {
      id: '/_main/guestbook'
      path: '/guestbook'
      fullPath: '/guestbook'
      preLoaderRoute: typeof MainGuestbookRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/blog': {
      id: '/_main/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof MainBlogRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/archive': {
      id: '/_main/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof MainArchiveRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/$': {
      id: '/_main/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof MainSplatRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/thoughts/': {
      id: '/_main/thoughts/'
      path: '/thoughts'
      fullPath: '/thoughts/'
      preLoaderRoute: typeof MainThoughtsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/api/signature/upload': {
      id: '/api/signature/upload'
      path: '/api/signature/upload'
      fullPath: '/api/signature/upload'
      preLoaderRoute: typeof ApiSignatureUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/guestbook/sign': {
      id: '/api/guestbook/sign'
      path: '/sign'
      fullPath: '/api/guestbook/sign'
      preLoaderRoute: typeof ApiGuestbookSignRouteImport
      parentRoute: typeof ApiGuestbookRoute
    }
    '/api/guestbook/check-eligibility': {
      id: '/api/guestbook/check-eligibility'
      path: '/check-eligibility'
      fullPath: '/api/guestbook/check-eligibility'
      preLoaderRoute: typeof ApiGuestbookCheckEligibilityRouteImport
      parentRoute: typeof ApiGuestbookRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/thoughts/$': {
      id: '/_main/thoughts/$'
      path: '/thoughts/$'
      fullPath: '/thoughts/$'
      preLoaderRoute: typeof MainThoughtsSplatRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/posts/$': {
      id: '/_main/posts/$'
      path: '/posts/$'
      fullPath: '/posts/$'
      preLoaderRoute: typeof MainPostsSplatRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainSplatRoute: typeof MainSplatRoute
  MainArchiveRoute: typeof MainArchiveRoute
  MainBlogRoute: typeof MainBlogRoute
  MainGuestbookRoute: typeof MainGuestbookRoute
  MainLoginRoute: typeof MainLoginRoute
  MainTalksRoute: typeof MainTalksRoute
  MainIndexRoute: typeof MainIndexRoute
  MainPostsSplatRoute: typeof MainPostsSplatRoute
  MainThoughtsSplatRoute: typeof MainThoughtsSplatRoute
  MainThoughtsIndexRoute: typeof MainThoughtsIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainSplatRoute: MainSplatRoute,
  MainArchiveRoute: MainArchiveRoute,
  MainBlogRoute: MainBlogRoute,
  MainGuestbookRoute: MainGuestbookRoute,
  MainLoginRoute: MainLoginRoute,
  MainTalksRoute: MainTalksRoute,
  MainIndexRoute: MainIndexRoute,
  MainPostsSplatRoute: MainPostsSplatRoute,
  MainThoughtsSplatRoute: MainThoughtsSplatRoute,
  MainThoughtsIndexRoute: MainThoughtsIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

interface ApiGuestbookRouteChildren {
  ApiGuestbookCheckEligibilityRoute: typeof ApiGuestbookCheckEligibilityRoute
  ApiGuestbookSignRoute: typeof ApiGuestbookSignRoute
}

const ApiGuestbookRouteChildren: ApiGuestbookRouteChildren = {
  ApiGuestbookCheckEligibilityRoute: ApiGuestbookCheckEligibilityRoute,
  ApiGuestbookSignRoute: ApiGuestbookSignRoute,
}

const ApiGuestbookRouteWithChildren = ApiGuestbookRoute._addFileChildren(
  ApiGuestbookRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TokenUsageRoute: TokenUsageRoute,
  WallRoute: WallRoute,
  ApiGuestbookRoute: ApiGuestbookRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiSignatureUploadRoute: ApiSignatureUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
